sudo: false # use container-based build
language: fortran
notifications:
    email: false

compiler: gfortran-6
os: linux
env: TESTID='gard_linux'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblapack-dev
      - libnetcdf-dev
      - gfortran-6
before_install:
  - source ci/gard_install_utils
  - gard_before_install
install:
   - gard_install
script:
  - gard_script
after_success:
  - gard_after_success
after_failure:
  - gard_after_failure
